name = stairs_recycle
title = Stairs Recycle
description = Turn stairs into slabs, different stairs, or back into blocks. Smelt cobble stairs into stone stairs. Highly recommended for Oneblock survival.
depends = default
optional_depends = stairs, elepower_machines
author = DumbDave961
